import { motion } from "framer-motion";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

export default function FAQSection() {
  const faqs = [
    {
      question: "Is ConsumerAI a replacement for a lawyer?",
      answer: "No, ConsumerAI is not a substitute for professional legal advice. We provide general information about consumer protection laws and help you understand your rights, but for specific legal advice tailored to your situation, you should consult with a qualified attorney."
    },
    {
      question: "How accurate is the legal information?",
      answer: "ConsumerAI is trained on up-to-date consumer protection laws, regulations, and legal cases. We strive for high accuracy, but laws can change, and interpretations may vary. Always verify important information with official sources when making decisions that could have legal consequences."
    },
    {
      question: "Is my conversation with ConsumerAI private?",
      answer: "Yes, your conversations are encrypted and private. We do not share your specific questions or data with third parties. We may use anonymized data to improve our AI systems, but this never includes personally identifiable information."
    },
    {
      question: "Can I use the letters generated by ConsumerAI in legal proceedings?",
      answer: "Yes, the letters and documents generated by ConsumerAI are designed to be legally compliant and can be used in correspondence with creditors, debt collectors, and credit bureaus. However, you should always review any document carefully before sending it."
    },
    {
      question: "What consumer laws does ConsumerAI cover?",
      answer: "ConsumerAI covers major federal consumer protection laws including the Fair Credit Reporting Act (FCRA), Fair Debt Collection Practices Act (FDCPA), Truth in Lending Act (TILA), and regulations from the Consumer Financial Protection Bureau (CFPB). We also cover relevant state consumer protection laws."
    }
  ];

  return (
    <section id="faq" className="py-16 bg-gray-50">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <motion.div 
          className="max-w-3xl mx-auto"
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
        >
          <div className="text-center">
            <h2 className="text-3xl font-extrabold text-gray-900 sm:text-4xl">
              Frequently Asked Questions
            </h2>
            <p className="mt-4 text-lg text-gray-500">
              Common questions about ConsumerAI and our services.
            </p>
          </div>
          
          <div className="mt-12 space-y-6">
            <Accordion type="single" collapsible className="w-full">
              {faqs.map((faq, i) => (
                <motion.div
                  key={i}
                  initial={{ opacity: 0, y: 10 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.3, delay: i * 0.1 }}
                >
                  <AccordionItem value={`item-${i}`} className="bg-white shadow overflow-hidden rounded-lg mb-4 border-none">
                    <AccordionTrigger className="px-4 py-5 sm:p-6 text-left text-lg font-medium text-gray-900 hover:no-underline">
                      {faq.question}
                    </AccordionTrigger>
                    <AccordionContent className="px-4 pb-5 sm:px-6 sm:pb-6">
                      <p className="text-base text-gray-500">{faq.answer}</p>
                    </AccordionContent>
                  </AccordionItem>
                </motion.div>
              ))}
            </Accordion>
          </div>
        </motion.div>
      </div>
    </section>
  );
}
